# Disqus
disqus:
  shortname: https-murilloyonamine-github-io
# Adapte as opções abaixo conforme necessário

url: ""
baseurl: ""
title: "Novo Portfolio Jekyll 4"
description: "Site migrado para Jekyll 4.x"
author_name: "Murillo"
resume_url: "/assets/files/resume.pdf"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-minifier
  - jemoji