# Disqus
disqus:
  shortname: murilloyonamine-github-io
# Adapte as opções abaixo conforme necessário

baseurl: ""
url: "https://murilloyonamine.github.io"
title: "Novo Portfolio Jekyll 4"
description: "Site migrado para Jekyll 4.x"
author_name: "Murillo"
resume_url: "/assets/files/resume.pdf"
future: true
# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier
  - jemoji

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/